Homework 1
fintech-kotlin/tsarev-cashback-service pull request #1
Opened 2020-02-23 00:31 UTC by Tsalexey

# Выполнено задание 1

## В процесс было сделано:
 - реализован card number masker
- реализован notification message generator
 - исправлен ER в 'test generating message' ввиду неработоспособности мока

## PR чеклист:
 - [ ] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [ ] Добавлен label с номером домашнего задания

2020-02-25 09:20 UTC, KazakovIgor requested changes
Необходимо доработать таким образом что бы тест NotificationMessageGeneratorImplTest завершался успешно в исходном виде

2020-02-25 09:20 UTC, KazakovIgor commented on src/test/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImplTest.kt
> +            "Спешим Вам сообщить, что на карту #####73837253400\n" +
Функция generateMessage() должна быть реализована таким образом что бы данный тест завершался успешно.
Сам тест исправлять не нужно.

2020-02-25 09:20 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +            else -> (cardNumber.takeIf { !it.isEmpty() }
Idea подсказывает, что можно использовать isNotEmpty()

2020-02-25 09:20 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +    val cardMasker: CardNumberMasker = CardNumberMaskerImpl();
1. Точка с запятой не нужна
2. Эта строчка вообще не нужна. У нас уже есть свойство cardNumberMasker (строка 6)

2020-02-25 09:20 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +                "Спасибо за покупку ${notificationMessageInfo.transactionDate.truncatedTo(ChronoUnit.MINUTES)}"
В kotlin можно использовать строки в тройных кавычках:
return """Уважаемый, ${notificationMessageInfo.name}! +
                "Спешим Вам сообщить, что на карту ${cardMasker.mask(notificationMessageInfo.cardNumber)}
                ...
                """.trimIndent()

2020-03-02 21:19 UTC, Tsalexey commented
ready to review

2020-05-06 23:53 UTC, closed without merging